export const codeblockLanguages = {
  '': 'Markdown',
  md: 'Markdown',
  markdown: 'Markdown',
  css: 'CSS',
  javascript: 'JavaScript',
  C: 'C',
  cpp: 'C++',
  python: 'Python',
  java: 'Java',
  html: 'HTML',
  json: 'JSON',
  xml: 'XML',
  yaml: 'YAML',
  sql: 'SQL',
  bash: 'Bash',
  shell: 'Shell',
  typescript: 'TypeScript',
  go: 'Go',
  rust: 'Rust',
  php: 'PHP',
  ruby: 'Ruby',
  kotlin: 'Kotlin',
  swift: 'Swift',
  r: 'R',
  lua: 'Lua',
  perl: 'Perl',
  powershell: 'PowerShell',
  dart: 'Dart',
  elixir: 'Elixir',
  txt: 'Plain Text',
  plaintext: 'Plain Text'
}
